name: Neille Caroline
favicon: null
layout_spectrum: 0.74992
typography_spectrum: 0.8809473391156644
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Neille Caroline
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e7cfb7'
    - '#7d8085'
    - '#2d2824'
    - '#5d5552'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
