layout_spectrum: 0.6950858447235078
typography_spectrum: 0.5998137651477009
color:
  brandColors:
    - '#FFFFFF'
    - '#FEC1B4'
    - '#EE9784'
    - '#AA5A59'
    - '#4E2A2C'
  brandStrength: 0.710640745004639
  lightness: 0.8658158271573484
  saturation: 0.8256961274892092
  rhythmicContrast: 0.31339733861386776
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Neille Caroline
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Langley Social Club
    url: 'http://langleyscr.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Scotch & Adventure
purpose: []
