name: Neille Caroline
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.2831541
title: Neille Caroline
purpose: []
color:
  saturation: 0.125448
  brandStrength: 0.625
  rhythmicContrast: 0.4910394
  brandColors:
    - '#ffffff'
    - '#e7cfb7'
    - '#7d8085'
    - '#2d2824'
    - '#5d5552'
  lightness: 0.5017921
cta:
  bucket: null
  version: null
  domain: null
favicon: null
typography_spectrum: 0.530466
analytics:
  twitter: null
  google: null
  facebook: null
